# Generated by Django 4.1.7 on 2023-08-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_withdraw_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='owner',
            new_name='user',
        ),
    ]
