# Generated by Django 4.1.7 on 2023-08-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_owner_dashboard_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
