# Generated by Django 4.1.7 on 2023-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
